"""Market-data port used by strategies and workers."""
from datetime import datetime
from typing import Protocol

from core.contracts import AssetInfo, DataSnapshot, FundamentalData, Market


class MarketDataAdapter(Protocol):
    async def snapshot(self, symbols: list[str], timeframe: str, as_of: datetime) -> DataSnapshot: ...


class ResearchMarketDataProvider(Protocol):
    """Provider contract for search, prices, and fundamental research data."""

    @property
    def market(self) -> Market: ...

    async def search(self, query: str) -> list[AssetInfo]: ...
    async def get_ohlcv(self, symbol: str, start_date: str, end_date: str, interval: str = "1d"): ...
    async def get_info(self, symbol: str) -> AssetInfo: ...
    async def get_fundamental(self, symbol: str) -> FundamentalData: ...
    async def get_tickers(self) -> list[AssetInfo]: ...
